displays:
-   id: 1
    name: Left
    driver:
        type: paged
        pages:
            -   type: ping
-   id: 2
    name: Right
    driver:
        type: paged
        pages:
            -   type: ntp
                filter:
                    instance: ntp.foxden.network:9100
            -   type: upspower
                filter:
                    hostname: ups-rack
